
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vaibhavatul47
 */
public class Forgot extends javax.swing.JPanel {

    /**
     * Creates new form Forgot
     */
    Image img;
    
    public Forgot() {
        initComponents();
	
	ImageIcon ic = new ImageIcon(getClass().getResource("/images/fpBg.jpg"));
       
        img = ic.getImage();
        
        Dimension d = new Dimension(img.getWidth(null), img.getHeight(null));
        setPreferredSize(d);
        setMinimumSize(d);
        setMaximumSize(d);
        setSize(d);
    }
    
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.drawImage(img, 0, 0, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ForgotPasswordPannel = new javax.swing.JPanel();
        fpPleaseLabel = new javax.swing.JLabel();
        fpEmailLabel = new javax.swing.JLabel();
        fpUsername = new javax.swing.JTextField();
        fpSecQuesLabel = new javax.swing.JLabel();
        fpSecAnsLabel = new javax.swing.JLabel();
        fpPassLabel = new javax.swing.JLabel();
        fpRePassLabel = new javax.swing.JLabel();
        fpSecurityQuestion = new javax.swing.JComboBox();
        fpSecurityAnswer = new javax.swing.JTextField();
        fpPassword = new javax.swing.JPasswordField();
        fpRePassword = new javax.swing.JPasswordField();
        fpSubmit = new javax.swing.JButton();
        fpGoBackLabel = new javax.swing.JLabel();

        setLayout(null);

        ForgotPasswordPannel.setOpaque(false);

        fpPleaseLabel.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        fpPleaseLabel.setForeground(new java.awt.Color(102, 102, 102));
        fpPleaseLabel.setText("Please enter the following details:");

        fpEmailLabel.setFont(new java.awt.Font("Shruti", 0, 14)); // NOI18N
        fpEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fpEmailLabel.setText("Email ID  ");

        fpUsername.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        fpSecQuesLabel.setFont(new java.awt.Font("Shruti", 0, 14)); // NOI18N
        fpSecQuesLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fpSecQuesLabel.setText("Your Security Question  ");

        fpSecAnsLabel.setFont(new java.awt.Font("Shruti", 0, 14)); // NOI18N
        fpSecAnsLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fpSecAnsLabel.setText("Answer  ");

        fpPassLabel.setFont(new java.awt.Font("Shruti", 0, 14)); // NOI18N
        fpPassLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fpPassLabel.setText("New Password  ");

        fpRePassLabel.setFont(new java.awt.Font("Shruti", 0, 14)); // NOI18N
        fpRePassLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fpRePassLabel.setText("Re-enter New Password  ");

        fpSecurityQuestion.setMaximumRowCount(6);
        fpSecurityQuestion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " -- Please Choose --", "What is your lucky number ?", "What is your pet name ?", "What is your birth place ?", "Who is your favourite teacher ?", "What is your school name ?", "What is your vehicle registration number ?", "What is the name of your village ?", "Who is your role model ?", "What is your childhood friend name ?", "What is your favourite subject ?" }));

        fpSubmit.setText("Submit");
        fpSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fpSubmitMouseClicked(evt);
            }
        });
        fpSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpSubmitActionPerformed(evt);
            }
        });

        fpGoBackLabel.setForeground(new java.awt.Color(204, 0, 0));
        fpGoBackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fpGoBackLabel.setText("Go Back");
        fpGoBackLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fpGoBackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fpGoBackLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ForgotPasswordPannelLayout = new javax.swing.GroupLayout(ForgotPasswordPannel);
        ForgotPasswordPannel.setLayout(ForgotPasswordPannelLayout);
        ForgotPasswordPannelLayout.setHorizontalGroup(
            ForgotPasswordPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForgotPasswordPannelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(ForgotPasswordPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fpPleaseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ForgotPasswordPannelLayout.createSequentialGroup()
                        .addGroup(ForgotPasswordPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fpSecQuesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fpSecAnsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fpPassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fpRePassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fpEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ForgotPasswordPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ForgotPasswordPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fpSecurityAnswer)
                                .addComponent(fpPassword)
                                .addComponent(fpRePassword)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ForgotPasswordPannelLayout.createSequentialGroup()
                                    .addComponent(fpGoBackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(fpSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(fpUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fpSecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        ForgotPasswordPannelLayout.setVerticalGroup(
            ForgotPasswordPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ForgotPasswordPannelLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(fpPleaseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ForgotPasswordPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fpUsername)
                    .addComponent(fpEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ForgotPasswordPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fpSecQuesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fpSecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ForgotPasswordPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fpSecAnsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fpSecurityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ForgotPasswordPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fpPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ForgotPasswordPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fpRePassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fpRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ForgotPasswordPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fpSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fpGoBackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );

        add(ForgotPasswordPannel);
        ForgotPasswordPannel.setBounds(140, 50, 711, 487);
    }// </editor-fold>//GEN-END:initComponents

    private void fpSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fpSubmitMouseClicked
        // TODO add your handling code here:
        startVerification();
    }//GEN-LAST:event_fpSubmitMouseClicked

    private void fpSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpSubmitActionPerformed
        // TODO add your handling code here:
        startVerification();
    }//GEN-LAST:event_fpSubmitActionPerformed

    private void fpGoBackLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fpGoBackLabelMouseClicked
        // TODO add your handling code here:
        reset();
        CardLayout card = (CardLayout) this.getParent().getLayout();
        card.show(this.getParent(), "loginCard");
        ((LoginFrame)this.getTopLevelAncestor()).loginFocus();
    }//GEN-LAST:event_fpGoBackLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ForgotPasswordPannel;
    private javax.swing.JLabel fpEmailLabel;
    private javax.swing.JLabel fpGoBackLabel;
    private javax.swing.JLabel fpPassLabel;
    private javax.swing.JPasswordField fpPassword;
    private javax.swing.JLabel fpPleaseLabel;
    private javax.swing.JLabel fpRePassLabel;
    private javax.swing.JPasswordField fpRePassword;
    private javax.swing.JLabel fpSecAnsLabel;
    private javax.swing.JLabel fpSecQuesLabel;
    private javax.swing.JTextField fpSecurityAnswer;
    private javax.swing.JComboBox fpSecurityQuestion;
    private javax.swing.JButton fpSubmit;
    private javax.swing.JTextField fpUsername;
    // End of variables declaration//GEN-END:variables

    void startVerification() {
        Person person = ((LoginFrame)this.getTopLevelAncestor()).person;
        
        person.uName = fpUsername.getText();
        int SecQues = fpSecurityQuestion.getSelectedIndex();
        String SecAns = fpSecurityAnswer.getText();
        String pwd = fpPassword.getText();
        String pwd2 = fpRePassword.getText();
        if (SecQues == 0 || SecAns.equals("") || person.uName.equals("") || pwd.equals("") || pwd2.equals("")) {
            JOptionPane.showMessageDialog(ForgotPasswordPannel, "Some Fields are empty!", "User Error", JOptionPane.DEFAULT_OPTION);
        }
        else if (!pwd.equals(pwd2)) {
            JOptionPane.showMessageDialog(ForgotPasswordPannel, "Passwords Do not Match!", "User Error", JOptionPane.DEFAULT_OPTION);
        }
        else if (person.knowsSecurityAns(SecQues, SecAns)) {
            person.updatePassword(pwd);
            JOptionPane.showMessageDialog(ForgotPasswordPannel, "Password Updated Successfully. Please Re-Login.", "Congratulations", JOptionPane.DEFAULT_OPTION);
            
            ((LoginFrame)this.getTopLevelAncestor()).initialisePerson();
            reset();
            CardLayout card = (CardLayout) this.getParent().getLayout();
            card.show(this.getParent(), "startCard");
        }
        else {
            //JOptionPane.showMessageDialog(ForgotPasswordPannel, "Invalid Email ID and Security Answer combination", "User Error", JOptionPane.DEFAULT_OPTION);
            fpPleaseLabel.setFont(new java.awt.Font("Times New Roman", 1, 18));
            fpPleaseLabel.setForeground(new java.awt.Color(180, 40, 40));
            fpPleaseLabel.setText("Contact Administrator if you forgot your Secutity Answer also.");
        }
        
        fpPassword.setText("");
        fpRePassword.setText("");
    }
    
    void resetPleaseLabel() {
        fpPleaseLabel.setFont(new java.awt.Font("Times New Roman", 2, 14));
        fpPleaseLabel.setForeground(new java.awt.Color(102, 102, 102));
        fpPleaseLabel.setText("Please enter the following details:");
    }
    
    void reset() {
        resetPleaseLabel();
        fpUsername.setText("");
        fpSecurityQuestion.setSelectedIndex(0);
        fpSecurityAnswer.setText("");
        fpPassword.setText("");
        fpRePassword.setText("");
        
    }
}
