
import java.awt.CardLayout;
import javax.swing.JOptionPane;


public class LoginFrame extends javax.swing.JFrame {
    
    public Person person;
    public LoginFrame() {
        initComponents();
	
        CardLayout card = (CardLayout)tray.getLayout();
        card.show(tray, "startCard");
        this.setResizable(false);
        this.setSize( 959, 600);
	
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tray = new javax.swing.JPanel();
        loginPanel1 = new LoginPanel();
        forgot1 = new Forgot();
        signup1 = new Signup();
        start1 = new Start();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MCU Login");

        tray.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout loginPanel1Layout = new javax.swing.GroupLayout(loginPanel1);
        loginPanel1.setLayout(loginPanel1Layout);
        loginPanel1Layout.setHorizontalGroup(
            loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        loginPanel1Layout.setVerticalGroup(
            loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        tray.add(loginPanel1, "loginCard");

        javax.swing.GroupLayout forgot1Layout = new javax.swing.GroupLayout(forgot1);
        forgot1.setLayout(forgot1Layout);
        forgot1Layout.setHorizontalGroup(
            forgot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        forgot1Layout.setVerticalGroup(
            forgot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        tray.add(forgot1, "forgotCard");

        javax.swing.GroupLayout signup1Layout = new javax.swing.GroupLayout(signup1);
        signup1.setLayout(signup1Layout);
        signup1Layout.setHorizontalGroup(
            signup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        signup1Layout.setVerticalGroup(
            signup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        tray.add(signup1, "signupCard");
        tray.add(start1, "startCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tray, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tray, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-976)/2, (screenSize.height-639)/2, 976, 639);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Forgot forgot1;
    private LoginPanel loginPanel1;
    private Signup signup1;
    private Start start1;
    private javax.swing.JPanel tray;
    // End of variables declaration//GEN-END:variables
    
    void changeBanner() {
        int CaptchaA = (int) ((Math.random() * 100) % 9 + 1);
        int CaptchaB = (int) ((Math.random() * 100) % 9 + 1);
        signup1.CaptchaAns = CaptchaA + CaptchaB;
        signup1.spCaptchaLabel.setText(CaptchaA + " + " + CaptchaB + " =  ");
    }
    
    void initialisePerson() {
        person.name = ""; // In Case if there are any reference to person object.
        person.uName = "";
        person.pass = "";
        person = null;
    }
    void setPersonLoginPanel() {
        loginPanel1.setPerson(person);
    }
    
    void showSignupLabelSignupPanel() {
        loginPanel1.showSignupLabel();
    }
    void hideSignupLabelSignupPanel() {
        loginPanel1.hideSignupLabel();
    }
    void resetPleaseLabelForgotPanel() {
        forgot1.resetPleaseLabel();
    }
    void changeFrame() {
	    
        if (person instanceof Customer) {
            new ShoppingFrame(person).setVisible(true);
            dispose();
        }
        else {
            Amin ob = new Amin(person);
            ob.setVisible(true);
            dispose();
        }
    }
    
    public void loginFocus() {
        loginPanel1.resetFocus();
    }
    
    public void SignupFoocus() {
        signup1.setFocusTOName();
    }

    
}
