/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Start.java
 *
 * Created on Mar 8, 2013, 2:29:51 AM
 */
/**
 *
 * @author hp
 */
import javax.swing.*;
import java.awt.*;
import java.net.URL;

public class Start extends javax.swing.JPanel {

	Image img;
	public Start() {
		initComponents();
		
	
		ImageIcon ic = new ImageIcon(getClass().getResource("/images/start.png"));
		
		img = ic.getImage();
		
		 Dimension size = new Dimension(img.getWidth(null), img.getHeight(null));
		 setPreferredSize(size);
		 setMinimumSize(size);
		 setMaximumSize(size);
		 setSize(size);
	}

	public void paintComponent(Graphics g)
	{
		super.paintComponent(g);
                g.drawImage(img, 0, 0, this);
	}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel1.setText("Customer Login");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        add(jLabel1);
        jLabel1.setBounds(170, 320, 170, 28);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel2.setText("Admin Login");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2);
        jLabel2.setBounds(700, 330, 140, 30);

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3);
        jLabel3.setBounds(340, 290, 90, 180);

        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        add(jLabel4);
        jLabel4.setBounds(540, 310, 150, 160);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        LoginFrame lframe = (LoginFrame)this.getTopLevelAncestor();
        lframe.person = new Customer();
        lframe.setPersonLoginPanel();
        lframe.showSignupLabelSignupPanel();
        CardLayout card = (CardLayout)getParent().getLayout();
        card.show(getParent(), "loginCard");
        ((LoginFrame)this.getTopLevelAncestor()).loginFocus();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        LoginFrame lframe = (LoginFrame)this.getTopLevelAncestor();
        lframe.person = new Administrator();
        lframe.setPersonLoginPanel();
        lframe.hideSignupLabelSignupPanel();
        CardLayout card = (CardLayout)getParent().getLayout();
        card.show(getParent(), "loginCard");
        ((LoginFrame)this.getTopLevelAncestor()).loginFocus();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        LoginFrame lframe = (LoginFrame)this.getTopLevelAncestor();
        lframe.person = new Customer();
        lframe.setPersonLoginPanel();
        lframe.showSignupLabelSignupPanel();
        CardLayout card = (CardLayout)getParent().getLayout();
        card.show(getParent(), "loginCard");
        ((LoginFrame)this.getTopLevelAncestor()).loginFocus();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       LoginFrame lframe = (LoginFrame)this.getTopLevelAncestor();
        lframe.person = new Administrator();
        lframe.setPersonLoginPanel();
        lframe.hideSignupLabelSignupPanel();
        CardLayout card = (CardLayout)getParent().getLayout();
        card.show(getParent(), "loginCard");
        ((LoginFrame)this.getTopLevelAncestor()).loginFocus();
    }//GEN-LAST:event_jLabel4MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
