/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vikash
 */

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class updateProfile extends javax.swing.JPanel {

    /**
     * Creates new form updateProfile
     */
    
    /*  public void askParent() {
	ShoppingFrame sf = (ShoppingFrame) this.getTopLevelAncestor();
	per = sf.per;
    } */
     
   Image img;
    public updateProfile() {
        initComponents();
        
        ImageIcon ic = new ImageIcon(getClass().getResource("/images/bgupdate.jpg"));
        img = ic.getImage();
        
        Dimension d = new Dimension(img.getWidth(null), img.getHeight(null));
        setPreferredSize(d);
        setMinimumSize(d);
        setMaximumSize(d);
        setSize(d);
        
    }
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
        g.drawImage(img, 0, 0, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jemaillabel = new javax.swing.JLabel();
        jlabelmobilenumber = new javax.swing.JLabel();
        jlabelcity = new javax.swing.JLabel();
        jusernamelabel2 = new javax.swing.JLabel();
        textemail_id = new javax.swing.JTextField();
        textusername = new javax.swing.JTextField();
        textcity = new javax.swing.JTextField();
        textmobile_number = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        savechanges = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        jemaillabel.setBackground(new java.awt.Color(255, 255, 255));
        jemaillabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jemaillabel.setForeground(new java.awt.Color(255, 255, 51));
        jemaillabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jemaillabel.setText("Email ID");

        jlabelmobilenumber.setBackground(new java.awt.Color(255, 255, 255));
        jlabelmobilenumber.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jlabelmobilenumber.setForeground(new java.awt.Color(255, 255, 51));
        jlabelmobilenumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlabelmobilenumber.setText("Mobile Number");

        jlabelcity.setBackground(new java.awt.Color(255, 255, 255));
        jlabelcity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jlabelcity.setForeground(new java.awt.Color(255, 255, 51));
        jlabelcity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlabelcity.setText("City");

        jusernamelabel2.setBackground(new java.awt.Color(255, 255, 255));
        jusernamelabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jusernamelabel2.setForeground(new java.awt.Color(255, 255, 51));
        jusernamelabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jusernamelabel2.setText("Name");

        textemail_id.setEditable(false);
        textemail_id.setBackground(new java.awt.Color(255, 153, 102));
        textemail_id.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        textemail_id.setToolTipText("Sorry!  Email/Username cannot be changed.");

        textusername.setBackground(new java.awt.Color(255, 153, 102));
        textusername.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        textcity.setBackground(new java.awt.Color(255, 153, 102));
        textcity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        textmobile_number.setBackground(new java.awt.Color(255, 153, 102));
        textmobile_number.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("French Script MT", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Your Data");

        savechanges.setBackground(new java.awt.Color(102, 102, 255));
        savechanges.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        savechanges.setText("Save Changes");
        savechanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savechangesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jusernamelabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlabelmobilenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jemaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jlabelcity, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textemail_id, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textmobile_number, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textcity, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(textusername, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(savechanges, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jusernamelabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jemaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabelmobilenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textmobile_number, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textusername, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textemail_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelcity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textcity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(savechanges, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void savechangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savechangesActionPerformed
               if(check()){
                    connection(textemail_id.getText());
                    ShoppingFrame.per.name = textusername.getText();
                    ShoppingFrame.per.mobileno = textmobile_number.getText();
                    ShoppingFrame.per.city = textcity.getText();
               } else {
                   JOptionPane.showMessageDialog(null," Enter the valid Entry");
               }
    }//GEN-LAST:event_savechangesActionPerformed

    boolean check(){
            if(textcity.getText().equals("") || textmobile_number.getText().equals("")|| textusername.getText().equals("")){
                    return false;
            }else {
                return true;
            }
    }
    
    void connection(String Id){
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
        try {
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", database.uname, database.password);
            String query = "Update customer set customer_name = ?, customer_mob = ?, customer_city = ? where customer_id = ?"+";";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1,textusername.getText());
            pst.setString(2, textmobile_number.getText());
            pst.setString(3, textcity.getText());
            con.close();
            JOptionPane.showMessageDialog(null, " Upadted Successfully");
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    
    public void SetFields() {
        textcity.setText(ShoppingFrame.per.city);
        textemail_id.setText(ShoppingFrame.per.uName);
        textmobile_number.setText(ShoppingFrame.per.mobileno);
        textusername.setText(ShoppingFrame.per.name);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jemaillabel;
    private javax.swing.JLabel jlabelcity;
    private javax.swing.JLabel jlabelmobilenumber;
    private javax.swing.JLabel jusernamelabel2;
    private javax.swing.JButton savechanges;
    private javax.swing.JTextField textcity;
    private javax.swing.JTextField textemail_id;
    private javax.swing.JTextField textmobile_number;
    private javax.swing.JTextField textusername;
    // End of variables declaration//GEN-END:variables

    
}
